name: Unzip five-osTheme-release

on:
  push:
    paths:
      - 'five-osTheme-release-v1.11.11.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Unzip the theme
        run: |
          unzip -o five-osTheme-release-v1.11.11.zip -d five-osTheme

      - name: Commit unzipped files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add five-osTheme/*
          git commit -m "Auto-unzipped five-osTheme-release-v1.11.11.zip"
          git push
