name: Unzip five-osTheme-release

on:
  push:
    paths:
      - 'five-osTheme-release-v1.11.11.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Unzip in place (no subfolder)
        run: unzip -o five-osTheme-release-v1.11.11.zip

      - name: Commit extracted files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Unzipped five-osTheme-release-v1.11.11.zip"
          git push
